### ISSUE TITLE
Make contact form functional, remove contact form example page.

### ISSUE THREAD

**Issue by amychurchwell** [amychurchwell/eattherainbowcatering#7]
Contact form should send email to `eattherainbowpdx@gmail.com`, interacts with netlify

**Comment by nathan-barrett** [comment]
Working on this now, boss!

**Comment by amychurchwell** [comment]
Per our text convo, I went ahead & did this issue ^_^

**Comment by nathan-barrett** [comment]
@amychurchwell  Nice!!
